name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Setup Expo and EAS
        run: |
          npm install -g eas-cli
          echo "${{ secrets.EXPO_TOKEN }}" > token.txt
          eas login --token $(cat token.txt)

      - name: Build APK with EAS
        run: eas build -p android --profile preview --non-interactive

      - name: Upload APK to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            **/*.apk
