name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Setup Expo and EAS
        run: |
          npm install -g eas-cli
          # لاگین کردن به اکسپو با استفاده از توکن ذخیره شده در Secrets
          eas login --non-interactive --token ${{ secrets.EXPO_TOKEN }}

      - name: Build APK with EAS
        run: eas build -p android --profile preview --non-interactive --no-wait

      - name: Upload APK to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            **/*.apk
